<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find yozakura_display)/robot/define.xacro"/>
    <xacro:include filename="$(find yozakura_display)/robot/config.xacro"/>
    <xacro:include filename="$(find yozakura_display)/robot/wheel_macro.xacro"/>

    <xacro:macro name="yozakura_body" params="parent_link">

        <joint name="joint_body_front_pitch" type="continuous">
            <axis xyz="0 1 0"/>
            <origin rpy="0 0 0"
                    xyz="0 0 0"/>
            <parent link="${parent_link}"/>
            <child link="virtualLink_body_front"/>
        </joint>

        <link name="virtualLink_body_front"/>

        <joint name="joint_body_front_roll" type="continuous">
            <axis xyz="1 0 0"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="virtualLink_body_front"/>
            <child link="body_front"/>
        </joint>

        <link name="body_front">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="${robotPackagePath}/${modelDataResourseFolder}/front_body.dae"/>
                </geometry>
            </visual>
        </link>

        <joint name="joint_body_back_pitch" type="revolute">
            <axis xyz="0 1 0"/>
            <limit lower="${DEG2RAD*bodyPitchAngle_min}" effort="1000.0"
                   upper="${DEG2RAD*bodyPitchAngle_max}" velocity="0.5"/>
            <origin rpy="0 0 0"
                    xyz="${-bodyFront_depth/2.0} 0 ${-bodyFront_height/2.0}"/>
            <parent link="body_front"/>
            <child link="body_link"/>
        </joint>

        <link name="body_link">
            <visual>
                <origin rpy="0 0 0"
                        xyz="${-bodyLink_length/2.0} 0 ${bodyFront_height/2.0}"/>
                <geometry>
                    <mesh filename="${robotPackagePath}/${modelDataResourseFolder}/body_roll.dae"/>
                </geometry>
            </visual>
        </link>

        <joint name="joint_body_back_roll" type="continuous">
            <axis xyz="1 0 0"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="body_link"/>
            <child link="body_back"/>
        </joint>

        <link name="body_back">
            <visual>
                <origin rpy="0 0 0"
                        xyz="${-bodyLink_length - bodyBack_depth/2.0} 0 ${bodyBack_height/2.0}"/>
                <geometry>
                    <mesh filename="${robotPackagePath}/${modelDataResourseFolder}/body_back.dae"/>
                </geometry>
            </visual>
        </link>

       
        <!-- WHEELS -->
        <xacro:combine_lr_wheels
                joint_name="joint_starwheel_front" parent="body_front"
                suffix="front" wheel_tread="${frontwheel_tread}">
            <origin rpy="0 0 0"
                    xyz="${frontwheelAxis_fromBodyCenter} 0 0"/>
        </xacro:combine_lr_wheels>

        <xacro:combine_lr_wheels
                joint_name="joint_starwheel_back" parent="body_back"
                suffix="back" wheel_tread="${backwheel_tread}">
            <origin rpy="0 0 0"
                    xyz="${backwheelAxis_fromBodyCenter} 0 ${bodyBack_height/2.0}"/>
        </xacro:combine_lr_wheels>

    </xacro:macro>
</robot>























