<?xml version="1.0"?>
<robot name="yozakura" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find yozakura_display)/robot/define.xacro"/>
    <xacro:include filename="$(find yozakura_display)/robot/config.xacro"/>
    <xacro:include filename="$(find yozakura_display)/robot/yozakura_arm2016.urdf.xacro"/>
    <xacro:include filename="$(find yozakura_display)/robot/yozakura_body.urdf.xacro"/>

    <!-- BODY -->
    <link name="root">
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </link> 

   <joint name="root_center" type="fixed">
          <origin rpy="0 0 0"  xyz="0 0 0.1"/>
          <parent link="root"/>
          <child link="center_yozakura"/>
    </joint>

    <link name="center_yozakura">
         <origin rpy="0 0 0" xyz="0 0 0"/>
    </link>

    <xacro:yozakura_body parent_link="center_yozakura"/>

    <!-- ARM -->
    <joint name="virtualjoint_arm_base" type="fixed">
        <origin rpy="0 0 0" xyz="${-armBase_fromBodyCenter_X} 0 ${bodyFront_height/2.0}"/>
        <parent link="body_front"/>
        <child link="virtual_arm_base"/>
    </joint>

    <link name="virtual_arm_base">
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </link>

    <xacro:yozakura_arm parent_link="virtual_arm_base"/>

</robot>























